### ISSUE TITLE
Arquivo csv não está carregando.

### ISSUE THREAD

**Issue by natelson81** [4llan/covid19-br-csv#1]
Boa tarde. Parabéns pelo excelente trabalho! O arquivo csv não está sendo carregado no repositório mais?

**Comment by 4llan** [comment]
Perdão, @natelson81. O MS mudou algumas coisas no dia primeiro de outubro e eu acabei me ausentando para resolver coisas pessoais. Farei a correção agora

**Comment by natelson81** [comment]
Obrigado pela atenção, 4llan! Perguntei pq achei o seu sistema muito bom, o melhor a nível de município que achei no github. Estou usando o repositório como fonte de dados (com a devida citação) para um dashboard covid feito para um consórcio público de saúde na Bahia, mas vi a licença e compreendi as restrições. De todo modo, parabéns por esse trabalho valioso! Sempre venho aqui na esperança de continuar a usar o seu sistema.

**Comment by 4llan** [comment]
Valeu, Natanelson! :) Fico feliz em saber que o código que disponibilizei
consegue ser útil para alguém.

Não se preocupe quanto a créditos, licenças e tudo mais. Eu escolhi a
unlicense porque eu iniciei o projeto com dois objetivos: criar uma base
histórica da modificação dos dados (cada commit ser um reflexo do que mudou
de um dia pro outro) e ter o histórico facilmente acessível em formato CSV.

Como configurei algumas automações, então sinta-se a vontade para dar fork
e modificar, mudar alguma coisa no código, mas automações ou no que seja
para se adequar as suas necessidades.

Vou tentar manter a rotina de geração sempre ativa e condizente com o que o
MS disponibiliza via API.

Grande abraço,
Allan

>
