### ISSUE TITLE
Pararam os updates?

### ISSUE THREAD

**Issue by pperrot1** [4llan/covid19-br-csv#2]

**Comment by 4llan** [comment]
Olá! Me desculpa, tive que me ausentar um pouco para resolver outras coisas. Lembrei que eu fiz alguma alteração que desativou as actions. Corrigirei agora

**Comment by 4llan** [comment]
Alterei a rotina para converter o arquivo disponibilizado no portal para tratar quando o dado esteja em XLSX, ZIP, CSV ou RAR. Caso o Ministério da Saúde altere novamente de forma a parar os updates, me avise por aqui, por gentileza. Obrigado
