### ISSUE TITLE
Sugestão: salvar csv comprimido em .gz

### ISSUE THREAD

**Issue by natelson81** [4llan/covid19-br-csv#3]
Boa noite, @4llan! Parece que o github tem limite de 100mb para pushs no repositório, né? Deixo a sugestão de seu código já subir o arquivo compactado com gzip para contornar essa limitação. 
Parabéns pelo trabalho, mais uma vez! Pudesse, colaborava diretamente na sugestão, mas sou principiante em codificação, entao ainda n me sinto seguro para colaborar, apenas sugerir. Saudações!

**Comment by 4llan** [comment]
Olá @natelson81, bom dia. Muito obrigado pela sua observação. Achei válido e interessante sua sugestão. Farei alguns testes implementando a compactação em gzip.

Eu achava que o histórico do arquivo CSV não pesaria tanto para o github por ser texto e o próprio git usar compactação em suas raízes. Enviar um arquivo já compactado de 2MB a cada dia pode ser que atinja algum outro limite do Github. Farei um teste usando Git Large File Storage (LFS) também.

**Comment by 4llan** [comment]
Limite atingido, mudei a branch principal para o esquema que testei para gerar o arquivo gzip. Agora é aguardar se o github workflow funcionará sem problemas.
